const brandIcons: {[key: string]: any} = {
  Lamborghini: require('../assets/images/lamborghini.png'),
  Smart: require('../assets/images/smart.png'),
  Ferrari: require('../assets/images/ferrari.png'),
  Volkswagen: require('../assets/images/volkswagen.png'),
  MercedesBenz: require('../assets/images/mercedes_benz.png'),
  Tesla: require('../assets/images/tesla.png'),
  Fiat: require('../assets/images/fiat.png'),
  LandRover: require('../assets/images/land_rover.png'),
  Nissan: require('../assets/images/nissan.png'),
  Maserati: require('../assets/images/maserati.png'),
  Bugatti: require('../assets/images/bugatti.png'),
  AstonMartin: require('../assets/images/aston_martin.png'),
  Chevrolet: require('../assets/images/chevrolet.png'),
  Honda: require('../assets/images/honda.png'),
  RollsRoyce: require('../assets/images/rolls_royce.png'),
  Audi: require('../assets/images/audi.png'),
  Cadillac: require('../assets/images/cadillac.png'),
  Kia: require('../assets/images/kia.png'),
  Hyundai: require('../assets/images/hyundai.png'),
  Polestar: require('../assets/images/polestar.png'),
  Mini: require('../assets/images/mini.png'),
  Mazda: require('../assets/images/mazda.png'),
  Dodge: require('../assets/images/dodge.png'),
  BMW: require('../assets/images/bmw.png'),
  Jeep: require('../assets/images/jeep.png'),
  Ford: require('../assets/images/ford.png'),
  profile: require('../assets/images/default_profile.png'),
};

export default brandIcons;
